# Generated by Django 3.1.5 on 2021-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('parcel_height', models.CharField(max_length=10)),
                ('parcel_width', models.CharField(max_length=10)),
                ('parcel_length', models.CharField(max_length=10)),
                ('parcel_weight', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('pickup_address', models.CharField(max_length=120)),
                ('deliver_address', models.CharField(max_length=120)),
                ('delman_name', models.CharField(max_length=150)),
                ('delman_phone', models.CharField(max_length=20)),
                ('delman_address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
